### ISSUE TITLE
NetspherePirates Discord Group

### ISSUE THREAD

**Issue by XXXTEMPTATION** [wtfblub/NetspherePirates#154]
I feel like there should be a discord group for this project, so when people need help they don't need to wait as long.

**Comment by Demon0no** [comment]
While I think that is a good idea, because it helps keeping this issue tracker clean of support threads (because that's not what an issue tracker is for in the first place), I'm not sure if wtfblub wants to handle support like this in the experimental phase we are in right now.
If wtfblub agrees with the decision for an official group though, I'd definately help out.

**Comment by XXXTEMPTATION** [comment]
That's good to hear, if he doesn't agree, we can do a community-ran support group.

**Comment by wtfblub** [comment]
Maybe when this project reaches a stable milestone.
