### ISSUE TITLE
How do I put values in each shop item?

### ISSUE THREAD

**Issue by herguet** [wtfblub/NetspherePirates#189]
How do I change the item values? And has item that does not have the image in the shop how do i solve it?

**Comment by HARUWEEN** [comment]
What do you mean with Item values? Items that don't have the image can be fixed by extracting the proper icons that are missing, adding them with resource tool, extracting iteminfo.x7 opening iteminfo.x7 and then find the item that's missing the icon, and add the file name to the "icon_image" string
