### ISSUE TITLE
SharpLzo dependencies

### ISSUE THREAD

**Issue by FreeDenny9700** [wtfblub/NetspherePirates#89]
On Linux with mono SharpLZO failed to Initialize. Fix this

**Comment by wtfblub** [comment]
Works fine on my debian and linux mint machine.

**Comment by FreeDenny9700** [comment]
Ok, today i test it on new version of linux

**Comment by FreeDenny9700** [comment]
Wtfblub it doesn't work for me. You are sure that you don't have installed other package over Mono-Complete?

I have tried to install on my Windows Server VPS but i have some error in windows. For fix this error i due install Visual Studio Community 2015 and his package and finally it work on Windows VPS.

For linux i don't have solution for now. i tried all but doesn't work.

**Comment by wtfblub** [comment]
Like the readme says you need Visual C++ Redistributable 2015 for windows. On linux i have no idea what you need, i just have a default dev environment. gcc, g++, make, autoconf, gettext are packages i installed after a default installation of debian and i compile mono myself.

I have no idea what exactly is required on linux since i compiled the SharpLzo library a long time ago without a proper project setup.

**Comment by FreeDenny9700** [comment]
Ok, thanks for response, i wait your notice

**Comment by FreeDenny9700** [comment]
With new version of Mono (Beta) and Build Essential, work perfectly.
Please Blub close Issues
